JS AO Construction
+ Live Server Preview fix + Fatal Build Destruction Fix

diff --git a/shell/build b/shell/build
--- a/shell/build
+++ b/shell/build
@@ -17,6 +17,9 @@ if [[ "$answer" == "dist" ]]; then
     GB_VER="dist"
 elif [[ "$answer" == "release" ]]; then
     GB_VER="release"
+else
+    echo "Invalid version name."
+    exit 1
 fi
 
 echo "Building for version: $GB_VER"
